return {
    LZ={
        SpawnPoint=Vector2.new(10,128);
        Bounds={Xmin=0,Xmax=-5000,Ymin=1000,Ymax=-1000};
        Chunks={
        {5,Vector2.new(0,256)};
        {5,Vector2.new(256,256)};
        {6,Vector2.new(384,256)}; --384
        {7,Vector2.new(512,256)};
        {8,Vector2.new(640,256)};
        {2,Vector2.new(768,512)};
        {7,Vector2.new(256*4,256)};
        {7,Vector2.new(256*4.5,256)};
        {7,Vector2.new(256*5,256)};
        {7,Vector2.new(256*5.5,256)};
        {7,Vector2.new(256*6,256)};
        {7,Vector2.new(256*6.5,256)};
        {7,Vector2.new(256*7,256)};
        {7,Vector2.new(256*7.5,256)};
        {7,Vector2.new(256*8,256)};
        {7,Vector2.new(256*8.5,256)};
        {7,Vector2.new(256*9,256)};
        {7,Vector2.new(256*9.5,256)};
        {7,Vector2.new(256*10,256)};
        {7,Vector2.new(256*10.5,256)};
        {7,Vector2.new(256*11,256)};
        {7,Vector2.new(256*11.5,256)};
        {7,Vector2.new(256*12,256)};
        {7,Vector2.new(256*12.5,256)};
        {7,Vector2.new(256*13,256)};


    };
};
}